services:
  scraparr:
    image: ghcr.io/thecfu/scraparr
    container_name: scraparr
    ports:
      - "7100:7100"
    volumes:
      - ./config.cnf:/scraparr/config/config.cnf # For v1 Release use /scraparr/config.cnf
