services:
  scraparr:
    image: ghcr.io/thecfu/scraparr
    container_name: scraparr
    ports:
      - "7100:7100"
    volumes:
      - ./config.yaml:/scraparr/config/config.yaml # For v1 Release use /scraparr/config.cnf and an ini File
