[project]
name = "scraparr"
version = "1.0.0"
description = "Prometheus Exporter for *Arr Suite"
readme = "README.md"
requires-python = ">=3.12"
dynamic = ["dependencies"]

[project.optional-dependencies]
dev = ["pytest>=7.0.0", "pytest-cov>=4.0.0"]

[project.scripts]
scraparr = "scraparr.scraparr:main"

[tool.setuptools.dynamic]
dependencies = {file = ["src/scraparr/requirements.txt"]}

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
