name: Create and publish the Main Docker Image

on:
  push:
    branches:
      - dev
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'uv.lock'
      - 'pyproject.toml'
  workflow_dispatch:

jobs:
  lint:
    uses: ./.forgejo/workflows/lint.yml

  test:
    uses: ./.forgejo/workflows/test.yml

  build-and-push-image:
    needs: [lint, test]
    uses: ./.forgejo/workflows/docker-build.yml
    with:
      codeberg_image: codeberg.org/thecfu/scraparr
      ghcr_image: ghcr.io/thecfu/scraparr
      dockerhub_image: thegameprofi/scraparr
      tags: type=raw,value=main
    secrets: inherit
