name: Create and publish a Release Image

on:
  release:
    types: [released]

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml

  build-and-push-image:
    needs: [lint, test]
    uses: ./.github/workflows/docker-build.yml
    with:
      registry_image: ghcr.io/${{ github.repository }}
      dockerhub_image: thegameprofi/scraparr
      tags: |
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=semver,pattern={{major}}
      check_latest_tag: true
      generate_attestation: true
    secrets: inherit
