name: Create and publish a Image for the PR

on:
  pull_request:
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'uv.lock'
      - 'pyproject.toml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write
  pull-requests: write

jobs:
  build-and-push-image:
    uses: ./.github/workflows/docker-build.yml
    with:
      registry_image: ghcr.io/thecfu/scraparr-dev
      tags: type=raw,value=pr${{ github.event.pull_request.number }}
      environment: pr-image
    secrets: inherit

  comment:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR image availability
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.ORVEX_PR_TOKEN }}
          message: |
            Docker image for this PR is available:
            ```
            docker pull ghcr.io/thecfu/scraparr-dev:pr${{ github.event.pull_request.number }}
            ```
