name: Pylint

on:
  pull_request:
    paths:
      - '**.py'
      - 'uv.lock'
      - 'pyproject.toml'
      - '**/requirements.txt'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
